# Generated by Django 5.0.6 on 2024-09-04 22:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
        migrations.AddField(
            model_name='card',
            name='damage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='card',
            name='synergies',
            field=models.ManyToManyField(blank=True, related_name='synergistic_with', to='CardManagement.card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='energy',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('synergistic_cards', models.ManyToManyField(blank=True, related_name='artifacts_with_synergies', to='CardManagement.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='artifact_synergies',
            field=models.ManyToManyField(blank=True, related_name='cards_with_synergies', to='CardManagement.artifact'),
        ),
        migrations.CreateModel(
            name='UpgradedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgraded_name', models.CharField(blank=True, max_length=100)),
                ('upgraded_description', models.TextField(blank=True)),
                ('upgraded_energy', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('upgraded_damage', models.IntegerField(blank=True, null=True)),
                ('original_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upgraded_version', to='CardManagement.card')),
            ],
        ),
    ]
