# Generated by Django 5.0.6 on 2024-09-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardManagement', '0002_remove_card_deck_card_damage_card_synergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(related_name='decks', to='CardManagement.card'),
        ),
    ]
