# Generated by Django 5.0.6 on 2024-09-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardManagement', '0003_deck_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_color',
            field=models.CharField(choices=[('Green', 'Green'), ('Red', 'Red'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Grey', 'Grey')], default='Grey', max_length=6),
        ),
    ]
