# Generated by Django 5.0.6 on 2024-09-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardManagement', '0004_card_card_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='artifact_synergies',
        ),
        migrations.CreateModel(
            name='Relic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('synergistic_cards', models.ManyToManyField(blank=True, related_name='relics_with_synergies', to='CardManagement.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='relic_synergies',
            field=models.ManyToManyField(blank=True, related_name='cards_with_synergies', to='CardManagement.relic'),
        ),
        migrations.DeleteModel(
            name='Artifact',
        ),
    ]
