# Generated by Django 5.0.6 on 2024-09-05 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardManagement', '0005_remove_card_artifact_synergies_relic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='energy',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
