# Generated by Django 5.0.6 on 2024-09-05 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardManagement', '0006_alter_card_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='energy',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='upgradedcard',
            name='upgraded_energy',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
