# Generated by Django 5.0.6 on 2024-09-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardManagement', '0008_alter_card_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_color',
            field=models.CharField(choices=[('Green', 'Green'), ('Red', 'Red'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Grey', 'Grey'), ('Black', 'Black'), ('White', 'White')], default='Grey', max_length=6),
        ),
    ]
