# Generated by Django 5.0.6 on 2024-09-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardManagement', '0009_alter_card_card_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='block',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upgradedcard',
            name='upgraded_block',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='damage',
            field=models.IntegerField(default=0),
        ),
    ]
