# Generated by Django 5.0.6 on 2024-09-05 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardManagement', '0010_card_block_upgradedcard_upgraded_block_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardManagement.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardManagement.deck')),
            ],
            options={
                'unique_together': {('deck', 'card')},
            },
        ),
    ]
