# Generated by Django 5.0.6 on 2024-09-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardManagement', '0011_deckcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare')], default='Common', max_length=8),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_color',
            field=models.CharField(choices=[('Green', 'Green'), ('Red', 'Red'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Grey', 'Grey'), ('Black', 'Black'), ('White', 'White')], default='White', max_length=6),
        ),
    ]
